export interface Product {
  drug_code: number
  din: string
  brand_name: string
  display_name: string
  company: string
  ai_group_no: string | null
  equivalence_key: string | null
  atc_number: string | null
  atc_name: string | null
  purpose?: string | null
  form: string | null
  route: string | null
  ingredient_label: string | null
  is_branded: number
  brand_rank: number
  brand_index?: number
  /**
   * A real per-unit price published by a Canadian government, or null.
   *
   * NULL FOR ~91% OF PRODUCTS, and that is correct rather than a gap to fill. See ADR-017: no
   * lawful, DIN-keyed Canadian retail price exists for any product in this catalogue, so the app
   * shows a price only where a government publishes one, and nothing at all where none does.
   *
   * There is deliberately no bare `price: number` field any more. The old `base_price` was
   * generated by a seeded PRNG for all 1,024 products and rendered with an "Est." prefix; the
   * prefix was load-bearing precisely because the number was invented.
   */
  benefit_price: BenefitPrice | null
  odb_ratio_pct: number | null
  odb_citation: string | null
}

/**
 * A per-unit amount a public drug plan reimburses a pharmacy. NOT a shelf price.
 *
 * `basis` is not optional and is not a tooltip. A payer price rendered as "$1.23" beside a
 * medicine is read as a shelf price by every user alive, so the basis ships in the same object as
 * the digits and the UI renders them in the same visual block.
 */
export interface BenefitPrice {
  din: string
  /** 'OBS' is a price a person read off a shelf tag — the only RETAIL price in the project. */
  jurisdiction: 'ON' | 'NS' | 'OBS'
  amountPerUnit: number
  /** "tablet", "capsule", "suppository", "mL", "g", "each" — makes "$X per ___" read correctly. */
  unit: string
  basis: string
  source: string
  /** ODB only, and only where the ministry reimburses less than the listed price. */
  ministryPays: number | null
  /** NS only — the interchangeable group the ceiling covers. It is not brand-specific. */
  interchangeableGroup: string | null
  /** Observed prices only: the pack the price was for, without which the number means nothing. */
  pack: { size: number; unit: string } | null
  /** Observed prices only: who saw it, where and when. */
  observed: { store: string; city: string; on: string; by: string; note?: string } | null
}

export interface EqGroup {
  key: string
  ai_group_no: string
  route: string
  form: string
  ingredient_label: string
  brand_anchor: number | null
  member_count: number
  has_alternatives: number
}

export interface DrugFactsRow {
  base: string
  label_count: number
  /** 1 only when the US label's sole active substance is this ingredient. Gates warning display. */
  single_ingredient: number
  label_substances: string | null
  purpose: string | null
  indications_and_usage: string | null
  warnings: string | null
  do_not_use: string | null
  ask_doctor: string | null
  ask_doctor_or_pharmacist: string | null
  when_using: string | null
  stop_use: string | null
  pregnancy_or_breast_feeding: string | null
  keep_out_of_reach_of_children: string | null
}

export interface PharmacyRow {
  id: string
  name: string
  brand: string | null
  lat: number
  lng: number
  address: string | null
  phone: string | null
  hours: string | null
  postcode: string | null
}

export interface SearchFilters {
  healthCanadaListedOnly: boolean
  nameBrandOnly: boolean
  /**
   * Replaces the price-band filter and the sort-by-cost toggle.
   *
   * Both of those operated on a generated number. With real prices covering 92 of 1,024 products,
   * a "$10 – $20" band is meaningless — the real figures are per-unit reimbursement amounts
   * running from $0.0114 to $15.65, and 91% of products have none at all. Sorting a list by a
   * value that 91% of it does not have puts the unpriced majority in an arbitrary order and
   * implies the ordering means something.
   *
   * What a user can actually ask for is the one thing the data supports: show me only the ones
   * where somebody published a real number.
   */
  publishedPriceOnly: boolean
}

export const NO_FILTERS: SearchFilters = {
  healthCanadaListedOnly: false,
  nameBrandOnly: false,
  publishedPriceOnly: false,
}

/** A search result: the branded anchor, then everything equivalent to it. */
export interface ResultSet {
  query: string
  branded: Product | null
  alternatives: Product[]
  group: EqGroup | null
  /** Products that matched but belong to other equivalence groups. */
  otherMatches: Product[]
}
