/**
 * Tab 3 on WEB — a real interactive map.
 *
 * react-native-maps compiles to react-native-web's UnimplementedView, so the web build needs its
 * own implementation. This file is web-only (Metro resolves MapScreen.native.tsx on iOS/Android),
 * and React Native Web renders through React DOM, so a plain <div> and a DOM map library are fine.
 *
 * WHY LEAFLET AND NOT MAPLIBRE (ADR-010):
 * MapLibre GL was the first choice — free OpenFreeMap vector tiles, no key, cartography that suits
 * the monochrome design. It loads its style and sources but never fires 'load' and paints nothing
 * in this environment, and the same failure reproduces in a BARE CDN page with no bundler involved,
 * so it is MapLibre's WebGL/worker path rather than anything in this app. Rather than ship a map
 * that could not be verified, this uses Leaflet: raster tiles, no WebGL, no web workers, verified
 * rendering. Same free-and-keyless property, one less way to fail.
 *
 * Tiles come from OpenStreetMap's standard layer. Their tile usage policy permits this scale of
 * use with attribution and a real User-Agent; the attribution control below is an ODbL obligation.
 */
import { useEffect, useMemo, useRef, useState } from 'react'
import { View, Text, Pressable, StyleSheet } from 'react-native'
import * as Location from 'expo-location'
import L from 'leaflet'
import 'leaflet/dist/leaflet.css'
import { PharmacyCard } from './PharmacyCard'
import { Icon } from './Icon'
import { PriceExplainer } from './PriceExplainer'
import { getProduct } from '../lib/repo'
import { nearbyFor, FALLBACK_LOCATION, type NearbyPharmacy } from '../lib/nearby'
import { useLayout, CONTENT_MAX } from './Shell'
import { radius, space, type, type Palette } from '../theme'
import { useTheme } from '../theme-context'

const TILES = 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'
const ATTRIBUTION = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'

/**
 * A pharmacy marker.
 *
 * These used to be price pills — "Est. $23.08" floating over a named, real pharmacy. That number
 * was generated by a seeded PRNG (ADR-017) and was the least defensible thing in the project: a
 * specific, false, financial claim about an identifiable business, rendered on a map so it read as
 * surveyed fact. The markers now carry what we actually know, which is that there is a pharmacy
 * there and what it is called.
 */
function pill(ph: NearbyPharmacy, color: Palette): L.DivIcon {
  const bg = ph.isNearest ? color.dark : color.surface
  const fg = ph.isNearest ? color.onDark : color.ink
  // Only the nearest carries its name. Eighteen name labels at downtown density overlap into an
  // unreadable pile — the old price pills were short enough to get away with it, "Shoppers Drug
  // Mart" is not. Everything else is a dot you can tap, with the name in the tooltip and in the
  // card that opens.
  if (!ph.isNearest) {
    const dot =
      `<span style="display:block;width:14px;height:14px;border-radius:50%;` +
      `background:${color.surface};border:3px solid ${color.ink};` +
      `box-shadow:0 1px 3px rgba(0,0,0,0.28);cursor:pointer;"></span>`
    return L.divIcon({ html: dot, className: '', iconSize: [14, 14], iconAnchor: [7, 7] })
  }
  const label = ph.name.length > 22 ? `${ph.name.slice(0, 21)}…` : ph.name
  const html =
    `<span style="` +
    `display:inline-block;font:600 11px system-ui,-apple-system,sans-serif;` +
    `padding:5px 9px;border-radius:999px;white-space:nowrap;` +
    `background:${bg};color:${fg};border:1.5px solid ${color.dark};` +
    `box-shadow:0 1px 3px rgba(0,0,0,0.22);cursor:pointer;">${escapeHtml(label)}</span>`
  // A real size matters: with [0,0] Leaflet renders a zero-box that cannot be clicked or focused,
  // and the pill floats away from its coordinate. Width tracks the label.
  const w = 30 + label.length * 6.2
  return L.divIcon({ html, className: '', iconSize: [w, 26], iconAnchor: [w / 2, 26] })
}

/** Pharmacy names come from OpenStreetMap, which is user-edited — never inject them raw. */
function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) =>
    ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c] as string))
}

export function MapScreen({ id }: { id: string }) {
  const styles = useStyles()
  const { color, scheme } = useTheme()
  const product = getProduct(Number(id))
  const { isWide } = useLayout()
  const [origin, setOrigin] = useState(FALLBACK_LOCATION)
  const [located, setLocated] = useState(false)
  const [selected, setSelected] = useState<NearbyPharmacy | null>(null)
  const [showPrices, setShowPrices] = useState(false)
  /**
   * Whether the tile server is actually answering. Without this, going offline left a grey
   * rectangle with "18 pharmacies near here" written confidently underneath it — the app looked
   * like it knew where things were while showing nothing at all.
   */
  const [tilesFailed, setTilesFailed] = useState(false)

  const container = useRef<HTMLDivElement | null>(null)
  const map = useRef<L.Map | null>(null)
  const layer = useRef<L.LayerGroup | null>(null)
  const tileLayer = useRef<L.TileLayer | null>(null)

  useEffect(() => {
    void (async () => {
      try {
        const { status } = await Location.requestForegroundPermissionsAsync()
        if (status !== 'granted') return
        const pos = await Location.getCurrentPositionAsync({})
        setOrigin({ lat: pos.coords.latitude, lng: pos.coords.longitude })
        setLocated(true)
      } catch {
        /* keep the downtown-Toronto fallback */
      }
    })()
  }, [])

  const nearby = useMemo(() => (product ? nearbyFor(product, origin, 18) : []), [product, origin])

  // Create the map once.
  useEffect(() => {
    if (!container.current || map.current) return
    const m = L.map(container.current, { attributionControl: true, zoomControl: true })
    m.setView([origin.lat, origin.lng], 13)
    const tiles = L.tileLayer(TILES, { attribution: ATTRIBUTION, maxZoom: 19 })
    // One failed tile is normal at the edge of a pan; a whole failed load is not. `tileerror`
    // fires per tile, so the flag is only raised once several in a row fail, and it clears the
    // moment any tile loads.
    let failures = 0
    tiles.on('tileerror', () => { if (++failures >= 3) setTilesFailed(true) })
    tiles.on('tileload', () => { failures = 0; setTilesFailed(false) })
    tiles.addTo(m)
    tileLayer.current = tiles
    layer.current = L.layerGroup().addTo(m)
    map.current = m

    // The flex container has no height on the first paint, so Leaflet measures zero and renders a
    // grey box until told otherwise.
    const ro = new ResizeObserver(() => m.invalidateSize())
    ro.observe(container.current)

    return () => {
      ro.disconnect()
      m.remove()
      map.current = null
      layer.current = null
    }
    // Deliberately once, on mount. `origin` is read here only to pick the FIRST view; every later
    // change to it is handled by the marker effect below, which re-fits the bounds. Re-running
    // this would tear the map down and rebuild it every time geolocation returned.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  /**
   * Tile treatment, re-applied whenever the theme flips.
   *
   * The design is deliberately monochrome and default OSM cartography is not, so the raster is
   * desaturated — that keeps the price pills the only thing on the screen with contrast, which is
   * the point of the tab. In dark mode it is additionally inverted: OSM publishes no dark raster
   * style, so without this the map stayed a sheet of white paper inside a near-black app, which
   * was both ugly and genuinely uncomfortable at night. Inverting a greyscale image is safe in a
   * way inverting a colour one is not — there are no hues to send to their opposites.
   *
   * This is a display filter. The tiles themselves are unmodified, which matters for the ODbL
   * attribution: we are not distributing a derived tile set.
   */
  useEffect(() => {
    const el = tileLayer.current?.getContainer()
    if (!el) return
    el.style.setProperty(
      'filter',
      scheme === 'dark'
        ? 'grayscale(1) invert(1) brightness(0.86) contrast(0.88)'
        : 'grayscale(1) contrast(0.92) brightness(1.06)',
    )
  }, [scheme])

  // Redraw the markers whenever the pharmacy set changes, or the palette flips.
  useEffect(() => {
    const m = map.current
    const g = layer.current
    if (!m || !g) return
    g.clearLayers()

    for (const ph of nearby) {
      L.marker([ph.lat, ph.lng], {
        icon: pill(ph, color),
        keyboard: true,
        alt: `${ph.name}, ${ph.distanceKm.toFixed(1)} kilometres away`,
        title: `${ph.name} — ${ph.distanceKm.toFixed(1)} km`,
      })
        .on('click', () => setSelected(ph))
        .on('keypress', () => setSelected(ph))
        .addTo(g)
    }

    if (located) {
      L.circleMarker([origin.lat, origin.lng], {
        radius: 7, color: color.surface, weight: 3, fillColor: color.accent, fillOpacity: 1,
      })
        .bindTooltip('You are here')
        .addTo(g)
    }

    // Fit to the pharmacies rather than a fixed zoom, so the price pills do not stack up in a
    // dense downtown.
    if (nearby.length > 1) {
      const bounds = L.latLngBounds(nearby.map((p) => [p.lat, p.lng] as [number, number]))
      bounds.extend([origin.lat, origin.lng])
      m.fitBounds(bounds, { padding: [46, 46], maxZoom: 15 })
    }
  }, [nearby, located, origin, color])

  if (!product) return <View style={styles.screen} />

  return (
    <View style={styles.screen}>
      <View style={styles.mapWrap}>
        <div ref={container} style={{ position: 'absolute', inset: 0 }} aria-label="Map of nearby pharmacies" />
        <View style={styles.banner} pointerEvents="none">
          <Text style={styles.bannerText} numberOfLines={2}>
            Real pharmacy locations from OpenStreetMap. Tap one for its address and directions.
          </Text>
        </View>

        {tilesFailed ? (
          <View style={styles.offline} pointerEvents="box-none">
            <View style={styles.offlineCard}>
              <Icon name="warning" size={22} color={color.noticeInk} />
              <Text style={styles.offlineTitle}>The map could not load</Text>
              <Text style={styles.offlineBody}>
                The tile server is not reachable — check your connection. The pharmacy list still
                works: the Stores tab has every one of them with addresses and directions.
              </Text>
            </View>
          </View>
        ) : null}
      </View>

      {selected ? (
        <View style={isWide ? styles.sheetWide : styles.sheet}>
          <Pressable
            onPress={() => setSelected(null)}
            accessibilityRole="button"
            accessibilityLabel="Close pharmacy details"
            style={styles.sheetClose}
          >
            <Icon name="close" size={18} color={color.inkSecondary} />
          </Pressable>
          <PharmacyCard pharmacy={selected} locationKnown={located} />
        </View>
      ) : (
        <View style={isWide ? styles.hintBarWide : styles.hintBar}>
          <Text style={styles.hintText}>
            {nearby.length} pharmacies near here. We don&apos;t know what any of them stock.
          </Text>
          <Pressable
            onPress={() => setShowPrices(true)}
            accessibilityRole="button"
            accessibilityLabel="Where our numbers come from"
            style={({ pressed }) => [styles.hintBtn, pressed && { opacity: 0.6 }]}
          >
            <Text style={styles.hintLink}>Where our numbers come from</Text>
            <Icon name="chevronRight" size={14} color={color.ink} />
          </Pressable>
        </View>
      )}

      <PriceExplainer visible={showPrices} onClose={() => setShowPrices(false)} />
    </View>
  )
}

const makeStyles = (color: Palette) => StyleSheet.create({
  screen: { flex: 1, backgroundColor: color.bg },
  mapWrap: { flex: 1, overflow: 'hidden', backgroundColor: color.surfaceAlt },
  banner: {
    // Left inset clears Leaflet's zoom control, which sits top-left. Capped rather than stretched
    // to the far edge: a one-line notice ruled across 1,380px of map reads as a browser warning
    // bar, not as a caption belonging to the prices underneath it.
    position: 'absolute', top: space.sm, left: 52, right: space.sm, maxWidth: 520, zIndex: 500,
    backgroundColor: color.noticeBg, borderWidth: 1, borderColor: color.noticeLine,
    borderRadius: radius.sm, paddingHorizontal: space.md, paddingVertical: 7,
  },
  bannerText: { ...type.small, color: color.noticeInk, fontSize: 12 },
  offline: {
    ...StyleSheet.absoluteFillObject, zIndex: 600,
    alignItems: 'center', justifyContent: 'center', padding: space.xl,
  },
  offlineCard: {
    maxWidth: 420, alignItems: 'center', gap: space.sm,
    backgroundColor: color.noticeBg, borderWidth: 1, borderColor: color.noticeLine,
    borderRadius: radius.lg, padding: space.xl,
  },
  offlineTitle: { ...type.subtitle, color: color.noticeInk, textAlign: 'center' },
  offlineBody: { ...type.small, color: color.noticeInk, textAlign: 'center' },
  sheet: {
    padding: space.lg, gap: space.sm,
    borderTopWidth: 1, borderTopColor: color.line, backgroundColor: color.surface,
  },
  sheetWide: {
    padding: space.lg, gap: space.sm,
    borderTopWidth: 1, borderTopColor: color.line, backgroundColor: color.surface,
    width: '100%', maxWidth: CONTENT_MAX, alignSelf: 'center',
  },
  sheetClose: { alignSelf: 'flex-end', minHeight: 44, minWidth: 44, alignItems: 'center', justifyContent: 'center' },
  hintBar: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: space.lg, paddingVertical: space.sm,
    borderTopWidth: 1, borderTopColor: color.line, gap: space.md,
  },
  hintBarWide: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: space.lg, paddingVertical: space.sm,
    borderTopWidth: 1, borderTopColor: color.line, gap: space.md,
    width: '100%', maxWidth: CONTENT_MAX, alignSelf: 'center',
  },
  hintText: { ...type.small, color: color.inkSecondary, flex: 1 },
  hintBtn: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 4, justifyContent: 'center' },
  hintLink: { ...type.smallStrong, color: color.ink },
})

/** Rebuilds the stylesheet when the palette changes (light <-> dark). */
function useStyles() {
  const { color } = useTheme()
  return useMemo(() => makeStyles(color), [color])
}
