import { useMemo } from 'react'
/**
 * "Where our numbers come from".
 *
 * REPLACES "How prices are estimated" (ADR-017). That screen existed to disclose a formula:
 * every price in the app was generated by `mulberry32(fnv1a(din + ':' + osmId))`, and the modal
 * showed the seed, the jitter band and the per-chain multipliers so the invention was at least
 * declared. The right fix was never a better disclosure — it was to stop inventing.
 *
 * A 23-source survey found no lawful, DIN-keyed Canadian retail price for any product in this
 * catalogue. So the app now shows a price only where a Canadian government publishes one, which is
 * 92 of 1,024 products, and shows nothing at all for the rest. This screen says exactly that.
 *
 * It is reachable from the footer rather than interrupting a flow, because it no longer has to
 * apologise for anything on the screen behind it.
 */
import { View, Text, Pressable, StyleSheet, Linking } from 'react-native'
import { Sheet } from './Sheet'
import { Icon } from './Icon'
import { meta } from '../lib/db'
import { products } from '../lib/dataset'
import { radius, space, type, type Palette } from '../theme'
import { useTheme } from '../theme-context'

export function PriceExplainer({ visible, onClose }: { visible: boolean; onClose: () => void }) {
  const { color } = useTheme()
  const styles = useStyles()
  const m = visible ? meta() : {}
  const priced = visible ? products.filter((p) => p.benefit_price).length : 0

  return (
    <Sheet visible={visible} onClose={onClose} title="Where our numbers come from" maxWidth={680}>
      <View style={styles.callout}>
        <Text style={styles.calloutText}>
          MediSense shows a price only where a Canadian government publishes one. That is{' '}
          {priced} of {products.length.toLocaleString()} products. For everything else it shows no
          price at all, rather than a guess.
        </Text>
      </View>

      <Text style={styles.h}>What is fully real</Text>
      <Text style={styles.p}>
        Which medicines exist, what is in them, at what strength and in what form, and which ones
        Health Canada groups as equivalent — all of it from the Drug Product Database. This is the
        part the app is actually built on, and it is authoritative.
      </Text>
      <Text style={styles.p}>
        Pharmacy names and locations are real too, from OpenStreetMap. What we do not know is which
        of them stocks a given product, or what it costs there.
      </Text>

      <Text style={styles.h}>The prices we do show</Text>
      <Text style={styles.p}>
        Two provinces publish, as open data, what their public drug plan reimburses a pharmacy for
        one tablet, millilitre or gram. Those figures are real, are tied to an exact Drug
        Identification Number, and can be checked against the source.
      </Text>
      <Text style={styles.p}>
        They are <Text style={styles.b}>not shelf prices</Text>. They exclude the pharmacy&apos;s
        markup, the dispensing fee and tax, and they apply only in that province. A tablet listed at
        three cents does not cost three cents at a till.
      </Text>

      <Text style={styles.h}>Why there is no price on most products</Text>
      <Text style={styles.p}>
        No Canadian pharmacy publishes shelf prices in a form anyone may reuse, and the retailers
        that show prices online prohibit collecting them automatically in their terms of use. Health
        Canada also removed every barcode from its database in 2025, so there is no reliable way to
        match one of these medicines to a specific product on a retailer&apos;s shelf. Rather than
        guess, the app links you to the retailer&apos;s own search.
      </Text>

      <Text style={styles.h}>Sources</Text>
      {[
        { label: m.drug_source, sub: m.drug_licence, url: m.drug_source_url },
        { label: 'Ontario Drug Benefit Formulary', sub: 'Open Government Licence – Ontario 1.0', url: m.price_source_url },
        { label: 'Nova Scotia Pharmacare Formulary', sub: 'Open Government Licence – Nova Scotia 1.1', url: 'https://data.novascotia.ca/Health-and-Wellness/Nova-Scotia-Formulary/wyjy-2gt4' },
        { label: m.pharmacy_source, sub: m.pharmacy_licence, url: 'https://www.openstreetmap.org/copyright' },
        { label: m.label_source, sub: m.label_licence, url: 'https://open.fda.gov/apis/drug/label/' },
      ].filter((s) => s.label).map((s) => (
        <Pressable
          key={s.label}
          onPress={() => s.url && Linking.openURL(s.url)}
          accessibilityRole="link"
          style={({ pressed }) => [styles.source, pressed && { backgroundColor: color.surfaceAlt }]}
        >
          <View style={{ flex: 1 }}>
            <Text style={styles.sourceTitle}>{s.label}</Text>
            <Text style={styles.sourceNote}>{s.sub}</Text>
          </View>
          <Icon name="external" size={16} color={color.inkSecondary} />
        </Pressable>
      ))}

      <Text style={styles.built}>
        Neither Health Canada, Ontario nor Nova Scotia endorses this project.
        {m.built_at ? ` Catalogue built ${m.built_at}.` : ''}
      </Text>
    </Sheet>
  )
}

const makeStyles = (color: Palette) => StyleSheet.create({
  callout: {
    backgroundColor: color.accentSoft, borderWidth: 1, borderColor: color.accentLine,
    borderRadius: radius.md, padding: space.lg,
  },
  calloutText: { ...type.body, color: color.accentInk },
  h: { ...type.subtitle, color: color.ink, marginTop: space.sm },
  p: { ...type.body, color: color.ink, maxWidth: 620 },
  b: { fontWeight: '700' },
  source: {
    flexDirection: 'row', alignItems: 'center', gap: space.md, backgroundColor: color.surface,
    borderWidth: 1, borderColor: color.lineMid, borderRadius: radius.md, padding: space.md, minHeight: 58,
  },
  sourceTitle: { ...type.smallStrong, color: color.ink },
  sourceNote: { ...type.small, color: color.inkTertiary, fontSize: 11 },
  built: { ...type.small, color: color.inkTertiary, fontSize: 11, marginTop: space.sm },
})

function useStyles() {
  const { color } = useTheme()
  return useMemo(() => makeStyles(color), [color])
}
