import { useMemo } from 'react'
/**
 * Price rendering — and, for 91% of the catalogue, the absence of one.
 *
 * ADR-017 replaced ADR-007. Every price in this app used to be generated by a seeded PRNG and
 * rendered with an "Est." prefix; the prefix was load-bearing precisely because the number was
 * invented. A 23-source survey established that no lawful, DIN-keyed Canadian retail price exists
 * for any product in this catalogue, so the invented numbers are gone and nothing replaced them
 * except the two real government sources that do exist.
 *
 * THE ONE RULE HERE: a public-plan per-unit reimbursement amount is a true number whose obvious
 * reading is false. "$1.23" beside a medicine is read as a shelf price by everyone. So the amount,
 * the unit and the basis render in ONE visual block and the basis is never behind a tap. That is
 * why this component takes the whole `BenefitPrice` object rather than a number.
 */
import { View, Text, Pressable, StyleSheet, Linking } from 'react-native'
import { radius, space, type, type Palette } from '../theme'
import { useTheme } from '../theme-context'
import { Icon } from './Icon'
import type { BenefitPrice, Product } from '../lib/types'

/** The compact form, for a card in a list. Amount + unit only, with the jurisdiction attached. */
/** How a price is worded depends entirely on where it came from. */
function labelFor(p: BenefitPrice): { where: string; a11y: string } {
  if (p.jurisdiction === 'OBS') {
    return {
      where: `${p.observed?.store ?? 'Observed'} · ${p.observed?.on ?? ''}`,
      a11y: `Shelf price, ${p.amountPerUnit.toFixed(2)} dollars for ${p.pack?.size ?? ''} ${p.unit}, seen at ${p.observed?.store ?? 'a store'}.`,
    }
  }
  const j = p.jurisdiction === 'ON' ? 'Ontario' : 'Nova Scotia'
  return {
    where: `${p.jurisdiction} public plan`,
    a11y: `${j} public plan price, ${p.amountPerUnit.toFixed(4)} dollars per ${p.unit}. Not a shelf price.`,
  }
}

export function BenefitPriceTag({ price }: { price: BenefitPrice }) {
  const styles = useStyles()
  const { where, a11y } = labelFor(price)
  const observed = price.jurisdiction === 'OBS'
  return (
    <View style={styles.tag} accessibilityLabel={a11y}>
      <Text style={styles.tagAmount}>
        ${observed ? price.amountPerUnit.toFixed(2) : price.amountPerUnit.toFixed(4)}
      </Text>
      <Text style={styles.tagUnit}>
        {observed && price.pack ? `for ${price.pack.size} ${price.pack.unit}` : `per ${price.unit}`}
      </Text>
      <Text style={styles.tagWhere} numberOfLines={1}>{where}</Text>
    </View>
  )
}

/** The full form, for a product page. Carries the basis and the citation inline. */
export function BenefitPriceBlock({ price }: { price: BenefitPrice }) {
  const styles = useStyles()
  const observed = price.jurisdiction === 'OBS'
  const where = observed
    ? 'Shelf price'
    : price.jurisdiction === 'ON'
      ? 'Ontario public plan price'
      : 'Nova Scotia public plan maximum'
  return (
    <View style={styles.block}>
      <Text style={styles.blockLabel}>{where}</Text>
      <View style={styles.blockAmountRow}>
        <Text style={styles.blockAmount}>
          ${observed ? price.amountPerUnit.toFixed(2) : price.amountPerUnit.toFixed(4)}
        </Text>
        <Text style={styles.blockUnit}>
          {observed && price.pack
            ? `for ${price.pack.size} ${price.pack.unit}`
            : `per ${price.unit}`}
        </Text>
      </View>
      {/* A pack price is only comparable once it is divided out. This is the number the whole app
          is for, and it exists only because a human recorded the pack size off the box. */}
      {observed && price.pack && price.pack.size > 0 ? (
        <Text style={styles.blockPerUnit}>
          ${(price.amountPerUnit / price.pack.size).toFixed(4)} per {price.pack.unit.replace(/s$/, '')}
        </Text>
      ) : null}
      {/* Not collapsible, not a tooltip, not a modal. */}
      <Text style={styles.blockBasis}>{price.basis}</Text>
      {price.ministryPays != null ? (
        <Text style={styles.blockBasis}>
          Listed at ${price.amountPerUnit.toFixed(4)}; the ministry reimburses $
          {price.ministryPays.toFixed(4)}, the lowest-cost-alternative rate.
        </Text>
      ) : null}
      <Text style={styles.blockSource}>{price.source}</Text>
    </View>
  )
}

/**
 * What a product with no published price shows instead.
 *
 * This is the honest replacement for a fabricated number, and it is deliberately not apologetic —
 * the equivalence claim above it is fully evidenced, and only the price is unavailable.
 */
export function NoPublishedPrice({ product }: { product: Product }) {
  const styles = useStyles()
  return (
    <View style={styles.none}>
      <Text style={styles.noneTitle}>No published price</Text>
      <Text style={styles.noneBody}>
        Prices are set store by store, and no Canadian pharmacy releases shelf prices in a form we
        are allowed to reuse. Compare the tags on the shelf, or look this up at a retailer.
      </Text>
      <WhereToBuy product={product} />
    </View>
  )
}

/**
 * "Where to buy" — a deep SEARCH link, never a product link.
 *
 * Two reasons, both hard. First, we cannot resolve which of a retailer's SKUs is DIN 01933531:
 * Health Canada deleted every UPC from the DPD, so the join would be fuzzy brand-name matching,
 * and sending someone to Advil Plus Acetaminophen when they asked about Advil is worse than
 * showing nothing — they would buy it. Second, a search URL is built entirely from data we own.
 *
 * This is a person tapping a link, not our fetcher crawling: robots.txt governs automated agents,
 * not navigation. The build pipeline never touches these hosts.
 *
 * Costco, Uniprix and Familiprix are deliberately absent — all three prohibit deep linking in
 * their terms (Costco grants "a limited, non-exclusive right to create a hypertext link to the
 * home page only").
 */
const RETAILERS: { name: string; url: (q: string) => string }[] = [
  // Walmart only, of the retailers checked. Its Terms of Use restrict extracting content but say
  // nothing about inbound links, so a link is clean.
  { name: 'Walmart.ca', url: (q) => `https://www.walmart.ca/en/search?q=${q}` },
  // Well.ca was here and had to be removed: its terms require WRITTEN APPROVAL before linking
  // ("If you wish to link to this Site, please contact us to obtain our written approval") and
  // restrict its content to "personal, non-commercial home use only". Costco, Uniprix and
  // Familiprix prohibit deep linking for the same reason. Amazon.ca's conditions are rendered
  // client-side and could not be read, so it is out until someone verifies them.
  { name: 'the web', url: (q) => `https://duckduckgo.com/?q=${q}+buy+canada` },
]

export function WhereToBuy({ product }: { product: Product }) {
  const { color } = useTheme()
  const styles = useStyles()
  // Brand plus strength: enough to land on the right shelf, built only from Health Canada fields.
  const query = encodeURIComponent(
    [product.display_name, product.ingredient_label?.split('+')[0]?.trim()]
      .filter(Boolean).join(' ').slice(0, 90),
  )
  return (
    <View style={styles.buy}>
      <View style={styles.buyRow}>
        {RETAILERS.map((r) => (
          <Pressable
            key={r.name}
            onPress={() => Linking.openURL(r.url(query))}
            accessibilityRole="link"
            accessibilityLabel={`Search ${r.name} for ${product.display_name}`}
            style={({ pressed }) => [styles.buyBtn, pressed && { opacity: 0.65 }]}
          >
            <Icon name="external" size={14} color={color.ink} />
            <Text style={styles.buyText}>Search {r.name}</Text>
          </Pressable>
        ))}
      </View>
      <Text style={styles.buyNote}>
        Opens the retailer&apos;s own search. MediSense is not affiliated with these stores and is
        not paid for these links.
      </Text>
    </View>
  )
}

/** Shown when the ODB Formulary gives a real, citable brand:generic ratio. */
export function SavingNote({ ratioPct, citation }: { ratioPct: number | null; citation: string | null }) {
  const styles = useStyles()
  if (ratioPct == null) return null
  if (ratioPct >= 99) {
    return (
      <View style={styles.saving}>
        <Text style={styles.savingTitle}>No saving here</Text>
        <Text style={styles.savingText}>
          Ontario&apos;s formulary lists the generic at the same per-unit price as the brand.
        </Text>
        {citation ? <Text style={styles.savingCite}>{citation}</Text> : null}
      </View>
    )
  }
  return (
    <View style={styles.saving}>
      <Text style={styles.savingTitle}>
        The generic costs about {Math.round(ratioPct)}% as much
      </Text>
      <Text style={styles.savingText}>
        Ontario&apos;s formulary lists generics of this ingredient at{' '}
        <Text style={{ fontWeight: '700' }}>{Math.round(ratioPct)}%</Text> of the brand&apos;s
        per-unit price. That is what the public plan pays rather than what you pay at the till —
        but the gap is real.
      </Text>
      {citation ? <Text style={styles.savingCite}>{citation}</Text> : null}
    </View>
  )
}

const makeStyles = (color: Palette) => StyleSheet.create({
  tag: { alignItems: 'flex-end' },
  tagAmount: { ...type.price, color: color.ink },
  tagUnit: { ...type.small, color: color.inkSecondary, fontSize: 12 },
  tagWhere: { ...type.micro, color: color.inkTertiary, fontSize: 10 },

  block: {
    backgroundColor: color.surfaceAlt, borderWidth: 1, borderColor: color.lineMid,
    borderRadius: radius.lg, padding: space.lg, gap: space.sm,
  },
  blockLabel: { ...type.overline, color: color.inkTertiary },
  blockAmountRow: { flexDirection: 'row', alignItems: 'baseline', gap: space.sm },
  blockAmount: { ...type.display, color: color.ink },
  blockUnit: { ...type.subtitle, color: color.inkSecondary },
  blockBasis: { ...type.small, color: color.inkSecondary, maxWidth: 620 },
  blockPerUnit: { ...type.bodyStrong, color: color.ink },
  blockSource: { ...type.small, color: color.inkTertiary, fontSize: 11 },

  none: { gap: space.sm },
  noneTitle: { ...type.subtitle, color: color.ink },
  noneBody: { ...type.small, color: color.inkSecondary, maxWidth: 620 },

  buy: { gap: space.sm, marginTop: space.xs },
  buyRow: { flexDirection: 'row', flexWrap: 'wrap', gap: space.sm },
  buyBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 7,
    borderWidth: 1, borderColor: color.lineMid, borderRadius: radius.pill,
    backgroundColor: color.surface, paddingHorizontal: space.lg, minHeight: 42,
  },
  buyText: { ...type.smallStrong, color: color.ink },
  buyNote: { ...type.small, color: color.inkTertiary, fontSize: 11, maxWidth: 620 },

  saving: {
    marginTop: space.sm, gap: 4, backgroundColor: color.verifiedBg,
    borderWidth: 1, borderColor: color.verifiedLine, borderRadius: radius.md, padding: space.lg,
  },
  savingTitle: { ...type.bodyStrong, color: color.verifiedInk },
  savingText: { ...type.small, color: color.verifiedInk },
  savingCite: { ...type.small, color: color.verifiedInk, fontSize: 11, opacity: 0.85 },
})

function useStyles() {
  const { color } = useTheme()
  return useMemo(() => makeStyles(color), [color])
}
